header:
  content: |
    Copyright (c) 2022 Thirty Meter Telescope International Observatory
    SPDX-License-Identifier: Apache-2.0

  paths-ignore:
    - "dist"
    - "licenses"
    - "**/*.md"
    - "**/*.json"
    - "**/*.cbor"
    - "**/*.http"
    - "**/*.yml"
    - "**/*.conf"
    - "**/*.hosts"
    - "*.*"
    - "LICENSE"
    - "NOTICE"
    - "jenkins/**"
    - ".github/**"
    - "**/target/**"
    - "notes/**"
    - "tools/**"


  comment: on-failure
