header:
  license:
    content: |
      Copyright (c) 2023 Thirty Meter Telescope International Observatory
      SPDX-License-Identifier: Apache-2.0
  paths-ignore:
    - "dist"
    - "licenses"
    - "**/*.md"
    - "**/*.json"
    - "**/*.cbor"
    - "**/*.http"
    - "**/*.yml"
    - "**/*.conf"
    - "**/*.hosts"
    - "*.*"
    - "LICENSE"
    - "NOTICE"
    - "jenkins/**"
    - "**/target/**"
    - "notes/**"
    - "tools/**"
    - "**/empty.scala"


  comment: on-failure
