header:
  paths-ignore:
    - "dist"
    - "licenses"
    - "**/*.md"
    - "**/*.json"
    - "**/*.cbor"
    - "**/*.http"
    - "**/*.yml"
    - "**/*.conf"
    - "**/*.hosts"
    - "*.*"
    - "LICENSE"
    - "NOTICE"
    - "jenkins/**"
    - ".github/**"
    - "**/target/**"
    - "notes/**"
    - "tools/**"
    - "**/empty"


  comment: on-failure
