# Copyright (c) [year] Thirty Meter Telescope International Observatory
# SPDX-License-Identifier: Apache-2.0

ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu