name: coursier

on:
  push:
    branches: [shivani/coursier-setup]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: 11
          apps: sbt sbtn
      - uses: coursier/cache-action@v5


      - name: Tests
        run: sbtn 'csw-location-apiJVM/test'