name: nightly

on:
  schedule:
    - cron: '30 18 * * *' # run at 00:00 AM IST

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11

      - name: Docker Permissions
        run: sudo chmod 666 /var/run/docker.sock

      - name: Package
        run: ./integration/scripts/package_integration.sh

      - name: Multi-NICs Docker
        run: ./integration/scripts/multiple_nic_test.sh

      - name: Paradox Validate Links
        run: sbt docs/Paradox/paradoxValidateLinks

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: csw-build