name: nightly

on:
  push:
    branches-ignore:
      - '**'
#on:
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Package
        run: ./integration/scripts/package_integration.sh

      - name: Multi-NICs Docker
        run: ./integration/scripts/multiple_nic_test.sh

      - name: Paradox Validate Links
        run: sbt docs/Paradox/paradoxValidateLinks

      - name: Build Status
        if: always()
        id: build_status
        run: |
          if [[ ${{job.status}} == Success ]]
          then
          echo ::set-output name=status_icon::'white_check_mark'
          echo ::set-output name=build_status::'SUCCESS'
          else
          echo ::set-output name=status_icon::'x'
          echo ::set-output name=build_status::'FAILURE'
          fi

      - name: Notify slack
        if: always()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"#csw-build\",\"text\":\":${{ steps.build_status.outputs.status_icon }}: ${{ steps.build_status.outputs.build_status }} \n https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}\"}'